In [1]:
# pip install numpy

In [3]:
import numpy as np

In [3]:
a=np.array([])
b=np.array([1,2,3,45,0])
c=np.array([[10,3,4],[4,5,8]])

In [4]:
a

array([], dtype=float64)

In [5]:
b

array([ 1,  2,  3, 45,  0])

In [6]:
c

array([[10,  3,  4],
       [ 4,  5,  8]])

In [7]:
type(a)

numpy.ndarray

In [8]:
type(b)

numpy.ndarray

In [9]:
type(c)

numpy.ndarray

In [10]:
a.ndim

1

In [11]:
b.ndim

1

In [12]:
c.ndim

2

In [13]:
a.size

0

In [14]:
b.size

5

In [15]:
c.size

6

In [16]:
c.shape

(2, 3)

In [17]:
n=np.array([[2,3,4,5] , [20,30,40,10] ,[200,300,600,700] ])

In [18]:
n.shape

(3, 4)

In [1]:
n[[1,2,3,4],[11,22,33,44],[5,7,9,90]]

NameError: name 'n' is not defined

In [2]:
import numpy as np

In [3]:
n=np.array([[2,4,6,8],[11,22,33,44],[33,44,55,66]])

In [4]:
n

array([[ 2,  4,  6,  8],
       [11, 22, 33, 44],
       [33, 44, 55, 66]])

In [5]:
n[0][0]

2

In [6]:
n[0,0]

2

In [7]:
n[1,2]

33

In [8]:
n[2,[0,1]]

array([33, 44])

In [9]:
np.arrange(11,8)

AttributeError: module 'numpy' has no attribute 'arrange'

# Reshape

In [10]:
np.arrange(12).reshape(3,4)

AttributeError: module 'numpy' has no attribute 'arrange'

In [11]:
np.sqrt(81)

9.0

In [12]:
n.max()

66

In [13]:
n.min()

2

In [14]:
n.mean()

27.333333333333332

In [15]:
n = np.array([[2,6,4,2],[24,34,56,32],[100,400,500,700]])

In [16]:
n

array([[  2,   6,   4,   2],
       [ 24,  34,  56,  32],
       [100, 400, 500, 700]])

In [17]:
n.argmax()

11

In [18]:
n.argmin()

0

In [19]:
n

array([[  2,   6,   4,   2],
       [ 24,  34,  56,  32],
       [100, 400, 500, 700]])

In [20]:
n*2

array([[   4,   12,    8,    4],
       [  48,   68,  112,   64],
       [ 200,  800, 1000, 1400]])

In [21]:
n+10

array([[ 12,  16,  14,  12],
       [ 34,  44,  66,  42],
       [110, 410, 510, 710]])

# Random

In [22]:
np.random.rand(2,2)

array([[0.37981778, 0.31668904],
       [0.00267204, 0.16823176]])

In [23]:
np.random.rand(2)

array([0.91854006, 0.55306891])

In [24]:
np.random.rand(2,2)

array([[0.22044623, 0.15494761],
       [0.82167314, 0.7275405 ]])

In [27]:
np.random.randint(9,90,12)

array([59, 35, 83, 69, 68, 10, 10, 19, 32, 70, 40, 35])

In [28]:
np.random.randint(9,90,12).reshape(4,3)

array([[51, 79, 42],
       [63, 68, 35],
       [41, 43, 70],
       [81, 36, 48]])

In [30]:
s=np.random.randint(9,90,12).reshape(4,3)

# 3D

In [4]:
d=np.array([[[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,55],[4,44],[6,66]]])

# Nan - not a number

In [6]:
x = np.array([12,56,np.nan,66,100,np.nan])

In [7]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [8]:
x.dtype

dtype('float64')